### ISSUE TITLE
Can i try?

### ISSUE THREAD

**Issue by Amit-Singh-op** [karthi1155/Miniproject_ltts#3]

**Comment by karthi1155** [comment]
Amitttt now what has happened is I have put build in the repo
Now the error is of Multiple main files:(

**Comment by karthi1155** [comment]
If you could help me out with this please would be great!!

**Comment by karthi1155** [comment]
CI-Coverage / build (pull_request) Failing after 28s — build this still says not approved because of multiple make files

**Comment by Amit-Singh-op** [comment]
OH damn finally problem solved :)

**Comment by karthi1155** [comment]
No It didnt:(
It stills says multiple main issue

**Comment by karthi1155** [comment]
Seee

**Comment by karthi1155** [comment]
Hey
Dude Thanks alot.
I was struggling a lot with this.
Thanks ya.

with regards
Karthika

**Comment by Amit-Singh-op** [comment]
yw lol

**Comment by karthi1155** [comment]
Lol😂😂

**Comment by Amit-Singh-op** [comment]
Haha
