### ISSUE TITLE
Unit testing 

### ISSUE THREAD

**Issue by Danush2208** [karthi1155/Miniproject_ltts#6]
Your unit testing shows nothing to be tested at least add one test case

mingw32-make: Entering directory 'D:/a/Miniproject_ltts/Miniproject_ltts/3.Implementation'
mingw32-make: Nothing to be done for 'testfile'.
mingw32-make: Leaving directory 'D:/a/Miniproject_ltts/Miniproject_ltts/3.Implementation'

**Comment by karthi1155** [comment]
I'm trying to do that but my function has no input parameters I'm trying to figure it out.
